import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import SideBar from "@/components/Sidebar/Sidebar";

import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Echoa - The all in one producitvity tool",
	description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
	<AuthProvider>
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<SideBar children={children}/>
			</body>
		</html>
	</AuthProvider>
	);
}
